site_name: cleair docs
site_url: !ENV [DOCS_SITE_URL, "https://docs.cleair.ai"]
repo_name: GitHub
repo_url: https://github.com/cleairlabs/cleair
docs_dir: content
site_dir: ../site
nav:
  - Getting started: index.md
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: media/cleair-logo-darkmode.png
  favicon: media/cleair-logo-darkmode.png
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
copyright:
  Cleair Labs
  # Made in Sweden 🇸🇪
extra:
  generator: false

# mkdocs serve -f docs/mkdocs.yml
